mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from Test import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path("google_sso/", include("django_google_sso.urls", namespace="django_google_sso")),
    path('',views.index,name='index'),
    path('auth/',include('users.urls')),
]

mysite/users/urls.py
from django.contrib import admin
from django.urls import path
from .views import register
from django.contrib.auth.views import LoginView,LogoutView

app_name="users"
urlpatterns = [
    path('register/',register,name='register' ),
    path('login/',LoginView.as_view(template_name="login.html"),name='login' ),
    path('logout/',LogoutView.as_view(template_name="logout.html"),name='logout' ),
]

mysite/Test/models.py
from django.db import models

# Create your models here.

mysite/users/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

mysite/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
class Registerform(UserCreationForm):
    email=forms.EmailField(label="Email")
    class Meta:
        model=User
        fields=['username','email','password1','password2']

mysite/Test/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request,'index.html')

mysite/users/views.py
from django.shortcuts import render
from .forms import Registerform
from django.contrib.auth.models import User

# Create your views here.

def register(request):
    form=Registerform(request.POST)
    if form.is_valid():
        form.save()
    return render(request,'register.html',context={'form':form})

mysite/Test/templates/index.html
<html>
  <head>
    <title>Testing site</title>
  </head>
  <body>
    <h1>Google SSO testing site</h1>
    <a href="{% url "users:register" %}">Register here</a><br>
    <a href="{% url "users:login" %}">Login Here</a><br>
    <a href="{% url "users:logout" %}">Logout Here</a><br>

    
  </body>
</html>

mysite/users/templates/login.html
<html>
  <head>
    <title></title>
  </head>
  <body>
    <h1>Login Page</h1>
    <form method="post">
        {% csrf_token %} {% for filed in form %} {{filed.name}} {{filed}}
        <br /><br />
        {% endfor %}
        <input type="submit" value="Submit" />
      </form>
</html>

mysite/users/templates/logout.html
<h1>{{user.username}} is sucessfully logout</h1>

mysite/users/templates/register.html
<html>
  <head>
    <title></title>
  </head>
  <body>
    <h1>Register Page</h1>
    <form method="post">
      {% csrf_token %} {% for filed in form %} {{filed.name}} {{filed}}
      <br /><br />
      {% endfor %}
      <input type="submit" value="Submit" />
    </form>
  </body>
</html>